title: Temp. Estimation of EV Batteries
description: An end-to-end Machine Learning Pipeline to estimate the core temperature of Electric Vehicle Battery Packs
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
